name: github_task
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animations: ^2.1.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_bounceable: ^1.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  page_transition: ^2.1.0
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
flutter_intl:
  enabled: true
